const INPUT_VALIDATE = 'INPUT_VALIDATE';
const SAVE_DATA = 'SAVE_DATA';
const LOAD_DATA = 'LOAD_DATA';
const CLEAR_DATA = 'CLEAR_DATA';
export {
  INPUT_VALIDATE,
  SAVE_DATA,
  LOAD_DATA,
  CLEAR_DATA,
};
